### ISSUE TITLE
Subsequent `setAnnotations` calls make highlights transparent

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#105]
## Context
In my app, I tried to implement a semi-controlled state for the annotations displayed on the screen. Each time a new annos list is received, it should be propagated into the `TextAnnotator` store. For that, I use the exposed [`setAnnotations`](https://github.com/annotorious/annotorious/blob/a9d328d0146a6b5304eccbc94d85745aed772813/packages/annotorious-core/src/model/Annotator.ts#L150) method.
 
## Issue
Unfortunately, when the `setAnnotations` is called more than once for the same annotator instance - highlights _become transparent_. However, they are still selectable and exist in the store 👀 
**_The issue happens for the `CANVAS` & `SPAN` renderers, but not the `CSS_HIGHLIGHTS`_** 🙌🏻 

## Demo

https://github.com/recogito/text-annotator-js/assets/68850090/81a6fc8b-8376-4c55-9a68-a90919d0b025

In the video, I used the `text-annotator-react` example, where I added the `MockApiSetter` component:
```tsx
const MockApiSetter = () => {
  const r = useAnnotator<W3CTextAnnotator>();

  useEffect(() => {
    if (!r) return;

    const testingAnnotations: W3CTextAnnotation[] = [ {...} ]

    const populateAnnotations = () => {
      r.setAnnotations(testingAnnotations, true)
      console.log('JUST SET ANNOTATIONS', r.getAnnotations());
    }

    populateAnnotations(); // Immediate invocation
    const intervalId = setInterval(populateAnnotations, 3500); // Invocation over the interval
    return () => clearInterval(intervalId);
  }, [r]);

  return null;
}
```
On the first `setAnnotations` call, the annotation is properly rendered and the highlight is visible. But after the 2nd one - the highlight becomes invisible/transparent.

**Comment by oleksandr-danylchenko** [comment]
I found that the `highlight.rects` upon the 2nd `setAnnotations` call is _an empty array_: 
![image](https://github.com/recogito/text-annotator-js/assets/68850090/344ac31a-8732-4678-aa68-aeb6111adbb9)

**Comment by rsimon** [comment]
Ah, interesting. Thanks for debugging. Still weird that they are clickable though, since this behavior is also enabled by the tree.

But for the immediate problem: I guess a quick fix would be to move deletion before creation. That should keep things working, but also trigger delete and create events for an annotation that was actually just updated. 

FWIW: for the store observer, replacing an annotation with an identical one would still count as an update operation, and I think that's perfectly valid. React, on the other hand, would not care. Therefore, I think it would make more sense to carry out proper diffing in the React wrapper, and then only perform the "real" delete/create/update operations that result from the operation?

**Comment by oleksandr-danylchenko** [comment]
> React, on the other hand, would not care

Could you please elaborate on that? As I don't fully understand why React "wouldn't care" 🤔 

Also, I saw that you've already added the `bulkUpsertAnnotations` method before: https://github.com/recogito/text-annotator-js/blob/6a2097075860d49dee2df27286bc9e23d5531707/packages/text-annotator/src/state/TextAnnotatorState.ts#L79-L98
That essentially resolves the immediate delete/create as an update. So, in my view, it would make sense to always use the "upsert". And when the `replace` option is passed - delete only the annotations that are not present in the incoming list 🤔

**Comment by oleksandr-danylchenko** [comment]
> Still weird that they are clickable though

Agree! Seems like only the rects `index` for the annotation is cleared out upon deletion, but not the `tree`. Because for the clicks processing only the latter is used

**Comment by oleksandr-danylchenko** [comment]
Yep, I double-checked the `remove` method for the `spatialTree` and found that not all rects are cleaned out from the `RBush` tree!

Before deletion:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/527303a1-f043-4125-96ec-e77a12730980)

Deletion works only over a single `rect`:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/4346a8ff-e877-43fa-b0fe-95a41275919e)

After deletion:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/260d240e-70de-4cbb-a995-54350a429e19)

**Comment by oleksandr-danylchenko** [comment]
Also, I noticed that the `set` function for the `spatialTree` is called 3 times! I can explain 2 times setting with the React 18 dev mode and double hooks invocation. But the 3rd one isn't clear to me yet. Nevertheless, an interesting part is that the tree contains duplicated rects for a single annotation. That's why even after the annotation removal it still remains in the tree!

**Comment by rsimon** [comment]
Yikes - thanks for all that sleuthing work! Duplicate rects in the spatial index explain that behavior exactly. Now the question is, how did they get there. I had problems previously, with RBush delete really only working well by object reference, but not by any other sort of equality. There might still be an issue where I'm trying to delete with an outdated object ref or something.

Concerning React: what I meant was that React doesn't really care about update _events_. If you replace a state object with an identical one, that might (or might not) re-render but, ultimately, doesn't change anything about the visible state of the UI. Annotorious is event-driven, meaning that if you replace an annotation with an identical copy in the store, that would totally count as an update operation, and fire events to all listeners. I think that's fine in terms of how things are designed in the core. 

But in the Annotorious React wrapper, you might not want to trigger actual updates internally, if React updates the state without actual changes on the values. Therefore, ideally the wrapper would incorporate a simple diffing algorithm, that forwards changes to the Annotorious core only in cases where actual values have changed.

(I'm already doing something similar elsewhere - would need to look - but the base code for this is already there.)

**Comment by oleksandr-danylchenko** [comment]
> But in the Annotorious React wrapper, you might not want to trigger actual updates internally

Ah, I got you now, thanks! So the idea is that the parent React component should prevent the `bulkAdd` or `bulkUpsert` from even starting if the resulting annotation will be the same. Yeah, that makes sense and surely brings some performance benefits.

**Comment by oleksandr-danylchenko** [comment]
> I had problems previously, with RBush delete really only working well by object reference, but not by any other sort of equality

I think one option would be to do deletion using the "custom `equals` function":
```ts
tree.remove(itemCopy, (a, b) => {
    return a.id === b.id;
});
```
But I suppose it'll just mask the duplication issue. As it would make more sense to store only a single set of rects for each annotation

**Comment by oleksandr-danylchenko** [comment]
> But I suppose it'll just mask the duplication issue. In my view, it would make more sense to store only a single set of rects for each annotation in the 1st place 🤔

I think it'll also get automatically resolved once we start marking the replacement of an annotation with an identical one _as an update_. Then state observer will properly call the `tree.update` for such targets and not the `tree.set` that does a bulk insertion into the tree. Which is performant, but not "intelligent" enough to resolve duplicates

**Comment by oleksandr-danylchenko** [comment]
> Duplicate rects in the spatial index explain that behavior exactly. Now the question is, how did they get there. I had problems previously, with RBush delete really only working well by object reference, but not by any other sort of equality. There might still be an issue where I'm trying to delete with an outdated object ref or something.

Actually, moving the `deleted` annotations processing higher, as I did in the #106 is enough to prevent the duplication of the rects in the `spatialTree`! That's because during the replacement the previously added rects will get cleared out and then the "new" ones will be added to the tree.
