### ISSUE TITLE
Annotator listeners are not fully removed using the `.off` method

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#107]
## Context
In my app, I register listeners for the `createAnnotation`, `updateAnnotation`, ... events on the annotator instance in the `useEffect` hook. But that hook has additional dependencies that can lead to its re-execution and the following removal/addition of the listeners.

## Issue
When the listeners are removed with the `.off` and added with the `.on` methods respectively, handlers start being invoked 2 times: 

https://github.com/recogito/text-annotator-js/assets/68850090/b3c3fe10-f138-45d3-a670-8fdc022ec0ff

I was able to replicate this issue using the `text-annotator-react` example ([source](https://pastebin.com/aNgWyLqR))

**Comment by oleksandr-danylchenko** [comment]
It's worth mentioning that despite how many more times I restart that hook, there only will be 2 invocations per listener

**Comment by oleksandr-danylchenko** [comment]
I also was able to replicate the issue using the A9S example:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/c12b3220-40d1-4ee3-b23f-a6354577f786)

```js
const handleCreate = (annotation) => {
  console.log('CREATE HANDLER', annotation);
}

const handleUpdate = (annotation) => {
  console.log('UPDATE HANDLER', annotation);
}

const registerListeners = () => {
  console.log('ADD LISTENERS');

  anno.on('createAnnotation', handleCreate);
  anno.on('updateAnnotation', handleUpdate);
}

const cleanupListeners = () => {
  console.log('CLEANUP LISTENERS');

  anno.off('createAnnotation', handleCreate);
  anno.off('updateAnnotation', handleUpdate);
}

registerListeners();

setTimeout(() => {
  cleanupListeners();
  registerListeners();
}, 400)
```

**Comment by oleksandr-danylchenko** [comment]
However, unlike in the text annotator, for A9S the number of observer invocations matches the number of registers:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/25340fe0-b81f-4ecc-b595-bbad035a61a7)

**Comment by oleksandr-danylchenko** [comment]
I found the mistake!
The `indexOf` check discards 0, although it's being a valid index:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/4706c7d2-bf32-40f5-952c-234664774eb9)
![image](https://github.com/recogito/text-annotator-js/assets/68850090/6664f334-42c1-4407-abb9-9ad6a54788f8)

**Comment by rsimon** [comment]
Argh - one of those classics... Dammit. Ok, yes, that should be `if (idx > -1)` of course. *shame*

**Comment by oleksandr-danylchenko** [comment]
It got resolved in https://github.com/annotorious/annotorious/pull/409. Therefore the issue can be closed once the `@annotorious/core` package gets bumped & `createLifecyleObserver` type will be fixed in the `text-annotator` package

**Comment by oleksandr-danylchenko** [comment]
It got resolved in https://github.com/annotorious/annotorious/pull/409. Therefore the issue can be closed once the `@annotorious/core` package gets bumped & `createLifecyleObserver` type will be fixed in the `text-annotator` package

**Comment by oleksandr-danylchenko** [comment]
⏫ Pinging about the https://github.com/annotorious/annotorious/pull/410#issuecomment-2167702677

> Could you please deploy this version? 🙏🏻🙏🏻🙏🏻
> It blocks me from proceeding to work on my app. When I try to link all the transitive deps locally - Vite doesn't pick up the changes ;(
