### ISSUE TITLE
Browser's selection highlight dimensions don't match the emulated highlights

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#109]
## Issue
When users select the text, both the default browser's selection highlight and the customly drawn highlight appear. Unfortunately, their dimensions don't match and that leads to the following views across browsers:
| Chrome | Safari | Firefox |
|--------|--------|--------|
| ![image](https://github.com/recogito/text-annotator-js/assets/68850090/6b624c46-f36f-4129-b1c4-9ecfbd36761e) | ![image](https://github.com/recogito/text-annotator-js/assets/68850090/cf6dbcde-0bef-4fcd-8e12-e66fdf3cceed) | ![image](https://github.com/recogito/text-annotator-js/assets/68850090/bed2a5ee-3d53-4234-b175-2b39b275e3f4) | 

That hanging bluish default selection background looks a bit out of place. Ideally, the emulated highlight should match its dimensions. Fortunately, that can be achieved by applying various sizes of compensations based on the browser:
| Chrome | Safari | Firefox |
|--------|--------|--------|
| ![image](https://github.com/recogito/text-annotator-js/assets/68850090/3a09be07-f081-4e0a-a3c3-2a66d86ce4b3) | ![image](https://github.com/recogito/text-annotator-js/assets/68850090/78721c7e-7f21-4a1b-9ffa-aed7290490c6) | ![image](https://github.com/recogito/text-annotator-js/assets/68850090/10d5e742-c677-48c8-a59a-b9a91ef952bc) | 

The padding can be applied in the concrete renderers, as I did for the `canvasRenderer`: 
```ts
// // Chrome
// const selectionHighlightTopCompensation = 3;
// const selectionHighlightBottomCompensation = 7;

// // Safari
// const selectionHighlightTopCompensation = 7;
// const selectionHighlightBottomCompensation = 7;

// Firefox
const selectionHighlightTopCompensation = 0;
const selectionHighlightBottomCompensation = 0;
offsetRects.forEach(({ x, y, width, height }) =>
  ctx.fillRect(
    x,
    y - selectionHighlightTopCompensation ,
    width,
    height + selectionHighlightBottomCompensation
  )
);
```

**Comment by oleksandr-danylchenko** [comment]
I'm surprised that `Firefox` is the only browser that doesn't apply some magical padding to its selection highlight

**Comment by rsimon** [comment]
Thanks for testing this out. I was thinking about whether I should just CSS-disable the native selection. But then left it because a) it's probably something that the host application would want to control; b) the native selection is, simply, rendered faster. Not a massive issue, and only for really large (XML - in our case) documents. But still.

About matching the sizes: I wonder how reliable those numbers are though, across different OSes and version increments...

**Comment by oleksandr-danylchenko** [comment]
I already tried disabling the native selection in my app and it didn't go that well 😅 

Especially when you have not-annotatable content in between the annotatable parts:

- The selection could stop abruptly when it's started on the not-annotatable element:

https://github.com/recogito/text-annotator-js/assets/68850090/21080513-89da-4d52-942b-1fedd9050027

- There could be 2 highlights at the same time 😆. One is made on a not-annotatable element, and the other one is emulated: 

[screen-capture (11).webm](https://github.com/recogito/text-annotator-js/assets/68850090/4fe5d915-8c33-4dfd-bd45-a5243af9447c)

- And the `Ctrl+A` acts weirdly then as well if you're focused on the not-annotatable element:

https://github.com/recogito/text-annotator-js/assets/68850090/655593f8-2311-44f1-ab16-3ce1ce7731e1

**Comment by oleksandr-danylchenko** [comment]
> About matching the sizes: I wonder how reliable those numbers are though, across different OSes and version increments...

That's a great question! I was about to experiment with that using the Browserstack. I'll get back with the results 🙌🏻

**Comment by oleksandr-danylchenko** [comment]
Aha, it's even more complex than I anticipated... The browser's selection highlight height can differ based on the selection element (`h` vs `p`) and the _text row number_ 🤯 

Here are the demos of the selection behavior across browsers with the:
```ts
const selectionHighlightTopCompensation = 0;
const selectionHighlightBottomCompensation = 0;
```

TL;DV;
`Firefox` is the most stable one and it always paints the selection hight using the same height.

### Chrome:

https://github.com/recogito/text-annotator-js/assets/68850090/a295843d-a219-483b-b9cb-8ff546b235ce

### Safari:

https://github.com/recogito/text-annotator-js/assets/68850090/4f029b1c-d4d4-4981-a617-60cddb135a6d

### Firefox:

https://github.com/recogito/text-annotator-js/assets/68850090/a161771b-61e5-48fd-b9bb-e3925df4b665

**Comment by oleksandr-danylchenko** [comment]
After many trials and tests in different environments, I would say that the _selection `selectionHighlightCompensation` should be removed and we should draw highlights using just the raw dimensions". Such a conclusion comes from multiple factors:
- Default browser's selection highlight height has [inconsistent behavior](https://github.com/recogito/text-annotator-js/issues/109#issuecomment-2192049392) across browsers / target elements / position of the text. This makes the creation of some generic compensation quite a moving target.
- Even when using the CSS highlights API - _there is a difference_ between the text selection highlight and the one drawn by CSS, _especially in Chrome_. 

https://github.com/recogito/text-annotator-js/assets/68850090/2667de32-640b-4d56-9215-7f6077fc357c

In the video, you can see that only in Chrome the default selection highlight is higher than the CSS one. Which begs the question whether that was intended behavior added by the Chromium devs 🤔

**Comment by oleksandr-danylchenko** [comment]
After many trials and tests in different environments, I would say that the _selection `selectionHighlightCompensation` should be removed and we should draw highlights using just the raw dimensions". Such a conclusion comes from multiple factors:
- Default browser's selection highlight height has [inconsistent behavior](https://github.com/recogito/text-annotator-js/issues/109#issuecomment-2192049392) across browsers / target elements / position of the text. This makes the creation of some generic compensation quite a moving target.
- Even when using the CSS highlights API - _there is a difference_ between the text selection highlight and the one drawn by CSS, _especially in Chrome_. 

https://github.com/recogito/text-annotator-js/assets/68850090/2667de32-640b-4d56-9215-7f6077fc357c

In the video, you can see that only in Chrome the default selection highlight is higher than the CSS one. Which begs the question whether that was intended behavior added by the Chromium devs 🤔
