### ISSUE TITLE
`Ctrl + A` doesn't make the annotation popup to appear

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#111]
## Issue
Currently, the `TextAnnotatorPopup` component appears only on the `pointerup` event: 
https://github.com/recogito/text-annotator-js/blob/36958ad904467777e082a4085f17e7415986c569/packages/text-annotator-react/src/TextAnnotatorPopup.tsx#L46-L52
But it ignores the keyboard selection that can be triggered by the `Ctrl + A` shortcut or a11y tools.

I suppose it's a shortcoming of the missing "selection completed" state in the store. Otherwise, we could make the `SelectionHandler` populate it upon meeting some predefined criteria. They can either be `pointerup` (sighted mouse users) or `keyup` (shortcuts and a11y tools support) event

## Demo

https://github.com/recogito/text-annotator-js/assets/68850090/18f0941b-e0f1-4249-b4b6-edebc7008c85

The popup renders only upon clicking somewhere on the page, initiating the `pointerup` event

**Comment by rsimon** [comment]
Addressed in PR #151
