### ISSUE TITLE
[`SPANS`] `underlineOffset` is incompatible with the `box-sizing: border-box`

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#115]
## Issue
The offset between the highlight and the underline is achieved using the `paddingBottom` of the `span`:
https://github.com/recogito/text-annotator-js/blob/36958ad904467777e082a4085f17e7415986c569/packages/text-annotator/src/highlight/span/spansRenderer.ts#L89-L90
However, that `span` also has the `height` priorly assigned:
 https://github.com/recogito/text-annotator-js/blob/36958ad904467777e082a4085f17e7415986c569/packages/text-annotator/src/highlight/span/spansRenderer.ts#L72

Therefore, when the popular `box-sizing: border-box` style is used, the `paddingBottom` applied after `height` becomes ineffective!

| `box-sizing: content-box` | `box-sizing: border-box` |
|--------|--------|
| ![image](https://github.com/recogito/text-annotator-js/assets/68850090/ad2e522e-5072-429c-8560-f22565f6e898) | ![image](https://github.com/recogito/text-annotator-js/assets/68850090/a6dfaaf9-4ba3-498a-ba62-cc104c4ab18f) |

**Comment by rsimon** [comment]
I think this one should be good to close. I merged the associated pull request.
