### ISSUE TITLE
The popup never shows up for the Android users ⚠️

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#145]
## Issue
Currently, the annotator popup is displayed when there's a selection + `pointerup` event present:
https://github.com/recogito/text-annotator-js/blob/992dd6771f3c01c1156446536001802b87823d39/packages/text-annotator-react/src/TextAnnotatorPopup.tsx#L68-L73
However, on Android, the `pointerup` event is **never dispatched**... Here's the events sequence of the selection:
<img width="598" alt="image" src="https://github.com/user-attachments/assets/e6002077-272c-409d-82c0-5ab0d0df8d46">

**Comment by oleksandr-danylchenko** [comment]
It’s worth mentioning that the events sequencing is its own nightmare…
Because it differs between the browsers + android:

### Selection:
| Chrome | Firefox | Android |
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/f11739a4-2a9f-46e3-aca9-60fbe4ae48ee) | ![image](https://github.com/user-attachments/assets/cc0530d1-83ee-489e-96be-55cf3c63160a) | ![image](https://github.com/user-attachments/assets/ca053a82-3643-4d07-be90-bf8cf5d79e76) | 

### Clicking on the textual content
| Chrome | Firefox | Android |
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/ab00044e-666e-49c2-a6fc-c7f43dfac66b) | ![image](https://github.com/user-attachments/assets/7cd08526-7b0a-4015-8277-34264c9c60a9) | ![image](https://github.com/user-attachments/assets/4ee88937-172c-4e0b-8584-4ca55ef1fb89) |

**Comment by oleksandr-danylchenko** [comment]
It seems like the Slab annotation tool faced the same limitation back then. So they display the _popup immediately_ when the selection starts!

**Comment by rsimon** [comment]
Just noting that this relates to [this discussion](https://github.com/recogito/text-annotator-js/issues/129#issuecomment-2382245079) about the popup not activating without the pointer up event, which is causing wider problems.
