### ISSUE TITLE
How can i add comments with text selections?

### ISSUE THREAD

**Issue by JINO-ROHIT** [recogito/text-annotator-js#156]
Thanks for this tool!

Is it possible to add comments with text selections with the text-annotator?
Also does this work with pdf instead of html files?

**Comment by rsimon** [comment]
Yes, it is possible to add comments - as far as the internal architecture is concerned. But there is no built-in popup, out of the box. In case you happen to use React: you can see an example for how you can use a React-based popup base component here:
https://github.com/recogito/text-annotator-js/blob/main/packages/text-annotator-react/test/App.tsx#L192-L196

Re PDF: yes! It's just as undocumented as this library is (for now). But here are two packages which extend the `text-annotator` and the `react-text-annotator` to work with PDFs:
https://github.com/recogito/pdf-annotator-js

**Comment by JINO-ROHIT** [comment]
Hi @rsimon when i run npm start inside the text-annotator-react, i run into this error

"[plugin:vite:import-analysis] Failed to resolve entry for package "@recogito/text-annotator". The package may have incorrect main/module/exports specified in its package.json."

**Comment by rsimon** [comment]
I think there may be differences between different node/npm/OS setups. (@recogito/text-annotator is defined as a peer dependency, but isn't automatically installed in all setups when running `npm install`.) For now, I'd recommend changing the package.json and moving (or copying?) `@recogito/text-annotator` from `peerDependencies` to `devDependencies`. This should properly download & install it regardless of your setup.

**Comment by JINO-ROHIT** [comment]
yeap thanks works now!
