### ISSUE TITLE
Question about `trimRange` for non-textual `startContainer` handling 🤔

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#23]
In the method `trimRange` there's a handling for the cases when either the `startContainer` or the `endContainer` are not the `Node.TEXT_NODE` type:
https://github.com/recogito/text-annotator-js/blob/80c2f9235ef27b2e57ff84a23d1f100a7b377e83/packages/text-annotator/src/utils/trimRange.ts#L11-L31
And on [line 19](https://github.com/recogito/text-annotator-js/blob/80c2f9235ef27b2e57ff84a23d1f100a7b377e83/packages/text-annotator/src/utils/trimRange.ts#L19) I noticed a small "weirdness". The comments say we're looking for the _first_ text child. 
**_Shouldn't we use `range.setStart` and not the `setEnd`?_** Am I missing something?🤔

**Comment by rsimon** [comment]
Good catch. Yes, I think you are correct - that might be an error on my part. Would need testing though... The purpose of the method is to handle edge cases where the selection starts/end on all sorts of non-text (images, layout block element etc.) nodes. Doesn't often happen if the annotated document is mostly text. But happens if markup is more complicated, and users click around frantically (which the usually do ;-) I'll try to test this on some of our own more complex docs.

**Comment by oleksandr-danylchenko** [comment]
### I think I noticed a few issues with the current `trimRange` method... 

1. In #65 I noticed that the `trimRange` [cannot be applied](https://github.com/recogito/text-annotator-js/issues/65#issuecomment-1966144252) to the ranges that were created after spitting on `.not-annotatable` elements
2. It creates weird collapsed ranges when the selection ends on an image:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/13a0fc0f-d03d-4018-bb75-717398b9b650)
W/o the `trimRange` - the selector is correct!
![image](https://github.com/recogito/text-annotator-js/assets/68850090/79c1ebe2-2cb8-4773-8596-1f50a65967b5)

**Comment by oleksandr-danylchenko** [comment]
And then there's a conceptual question about the role of the `trimRange` in general 🤔 
> The purpose of the method is to handle edge cases where the selection starts/ends on all sorts of non-text (images, layout block element etc.) nodes.

So the trim will discard the non-text nodes only if they are _at the edges_ of the selection... but not in the middle... Although in both cases user _selected those nodes_.

For example, if I select the `text` + `img`, the latter will get removed. But if the selection is `text` + `img` + `text` - the image is kept in! Then why was it discarded in the first place 🤷🏻‍♂️ 
The same can be said for any other non-textual nodes that are trimmed on the edges, but not excluded from the middle of the selection. 

I feel like the concept of not annotatable elements and "selection with holes" fits such elements more 🤔

**Comment by oleksandr-danylchenko** [comment]
Temporary closing this issue in favor of a more broad one - #66
