### ISSUE TITLE
Obsolete bounds returned from the `getAnnotationBounds` on scroll

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#25]
## Issue
When I started using the custom popover that snaps to the annotation itself - I noticed a weird positioning behavior on the scroll...

https://github.com/recogito/text-annotator-js/assets/68850090/c2025634-4e22-46bb-b0be-b39c1ab687b1

To anchor the popover to the anno, I used the [virtual element](https://popper.js.org/docs/v2/virtual-elements/). And its coordinates were obtained from the next method:
https://github.com/recogito/text-annotator-js/blob/80c2f9235ef27b2e57ff84a23d1f100a7b377e83/packages/text-annotator/src/state/TextAnnotatorState.ts#L117-L131
As I understood, the `getAnnotationBounds` obtains the anno's `rects` from the `spacialTree`, which caches the rendered annotations `rects` **_including the viewport offsets_**! 
![image](https://github.com/recogito/text-annotator-js/assets/68850090/af7120fe-4c50-44cf-907a-a3375735c895)
I think that's expected and it lifts the relative positioning burden from the consuming app. Also, it positions the popup properly before the scroll.

---

But... That caching starts to play against us, as soon as a user scrolls the page...
![image](https://github.com/recogito/text-annotator-js/assets/68850090/fb1353ff-4849-46eb-bac8-0b3083555fe1)
That's because the spacial tree positions get recalculated only on resizing, but not on scroll: 
https://github.com/recogito/text-annotator-js/blob/80c2f9235ef27b2e57ff84a23d1f100a7b377e83/packages/text-annotator/src/highlight/highlightLayer.ts#L154-L161
https://github.com/recogito/text-annotator-js/blob/80c2f9235ef27b2e57ff84a23d1f100a7b377e83/packages/text-annotator/src/highlight/highlightLayer.ts#L145

## Possible solutions
1. Call `store.recalculatePositions` in the scroll event handler. The most straightforward approach, but it'll hurt the overall performance of the page. Especially if there are many annotations present.
2. Recalculate the position only for the annotations in the viewport. A bit better, but it feels like a band-aid that will still hurt the performance on larger screens.
3. _Expose a method that will allow to get a "raw" annotation `rects`, w/o viewport offsets._
Seems like the `highlightLayer` already uses the "live" and "raw" `rects` to properly position the highlighted areas on scroll.
I would personally vote for this one. Because it's the most flexible and gives more decision-making freedom for the consuming app.

**Comment by rsimon** [comment]
Hi, I need to look into this in more detail when there's more time. But, in general:

- The `getAnnotationBounds` method is __not__ supposed to get the live bounds! I.e. you should not use it for positioning popup elements.
- Instead, what happens is that the spatial tree builds a 2D map of all annotations on load, relative to the container element. This, then is used during scrolling to query which annotations are in view, and need to be rendered to the canvas.
- This is also the reason why the spatial tree need to be rebuilt on resize (because the whole layout might change), but __not__ on scroll. (Because the map, relative to the container element, does not change.)

The whole process is not perfect at the moment, however. Because the relative offset (= origin of the spatial tree) is determined also by the `scrollTop` position of the text container at the time the page loads - which may not be 0. But I've been considering this an edge case for now, and it should actually be easy to fix further down the line.

Anyways: TL;DR, you'd need to compile your own live popover position based on the annotation bounds __plus the current scroll offset__.

BTW: the built-in popup component, if I remember correctly, gets around this by making the popup a child of the text container.

**Comment by rsimon** [comment]
If you have the annotation bounds, I think you should be able to follow a similar approach as the highlighter, as you say. In every render cycle, it fetches the clientBounds of the container, and then uses the top/left value to offset the annotation bounds.

https://github.com/recogito/text-annotator-js/blob/main/packages/text-annotator/src/highlight/highlightLayer.ts#L82-L125

**Comment by oleksandr-danylchenko** [comment]
> In every render cycle, it fetches the clientBounds of the container, and then uses the top/left value to offset the annotation bounds.

Yeah, I saw that code and also tried to use the "live" viewport dimensions with the annotations bounds obtained from the `getAnnotationBounds`. But, unfortunately, it didn't work out at all because:
1. The annotation bounds on the initial selection are already specified with the offsets. So adding/removing something from the pos. will lead to a redundant shift.
2. If I select the anno after I scroll a bit - I'll get obsolete annotation bounds from the `getAnnotationBounds` _with offsets_ that are no longer relevant and adding the current viewport offsets won't make much sense 🤷🏻‍♂️

**Comment by oleksandr-danylchenko** [comment]
> If you have the annotation bounds

I'm not sure about that... Previously I tried to get the **bounds** from the `getAnnotationBounds`, but it didn't work out... Are there alternatives to obtain **bounds**?

---

Using the individual `rects` as it does in the `hightlightLayer` for the Popup can be pretty inconvenient 🤔. The consumer app will need to find "the highest rect" first and only then add the "live" viewport offsets

**Comment by oleksandr-danylchenko** [comment]
Also, I'm a bit puzzled how the `redraw` function still can obtain the "live" rects from the same `spacialTree` that is not being recalculated on scroll 👀 
Have already spent some time looking through the code but still didn't get the magical enlightening :(

**Comment by rsimon** [comment]
I'd need a bit more time to look into this than I have right now. But the spatial tree as such remains static, with offsets computed from the top of the scrollable element. (Or more precisely, the initial position of the scrolling element on page load, which isn't ideal as written above.) I believe there might also be different get-bounds-something methods that work based on the `.getClientBounds` for the DOM range (which would be relative to the screen) and the bounds stored in the index.

FWIW: if you have a handle on the annotation, you could actually work around this by getting the current client bounds of the range (part of the selector) on every scroll?

**Comment by rsimon** [comment]
Yep, that's it :-)

**Comment by oleksandr-danylchenko** [comment]
> FWIW: if you have a handle on the annotation, you could actually work around this by getting the current client bounds of the range (part of the selector) on every scroll?

Hmm, that's an idea 🤔 
Not sure why I didn't consider this option before
