### ISSUE TITLE
`trimRange` unexpectedly prevents selection started from the nested elements

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#27]
## Issue
I noticed that the selection that follows a nested element gets unexpectedly interrupted by the `trimRange` method. It happens when the `range` obtained from the `document.getSelection().getRangeAt(0)` _gets mutated_ on the `selectionchange` event handling.

---

In the video, I depicted that the selection can freely go _before_ the nested `span`. But when I was trying to select anything after - nothing was happening. And right before the selection gets blocked - `trimRange` mutates the selection range: 
<img width="828" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/f9c4d8b0-cc22-46af-b7a1-52358f036b85">

https://github.com/recogito/text-annotator-js/assets/68850090/263f05d4-7ca9-47a8-8a56-581ecd1d461a

### Simple, yet effective 
Add cloning of the selection range before processing it in the `trimRange`: 
https://github.com/recogito/text-annotator-js/blob/80c2f9235ef27b2e57ff84a23d1f100a7b377e83/packages/text-annotator/src/SelectionHandler.ts#L77
⏬⏬⏬
```tsx
const trimmed = trimRange(ranges[0].cloneRange());
``` 
### More complicated, but future-proof
Move the selection range processing to the `pointerup` event handler. At that stage, the selection will be complete and we can do any mutations we want to the selection range.
Such a suggestion/prompt has already been expressed in another issue - https://github.com/recogito/text-annotator-js/issues/24 (Omission of the annotable elements within the text). It will help to execute any "heavy" traversals, splitting, etc. on the final range w/o hurting the "live" selection performance

**Comment by oleksandr-danylchenko** [comment]
I think for now I can add PR for the simpler solution and the complicated one can be done as part of the #24 impl

**Comment by oleksandr-danylchenko** [comment]
Also, I noticed that for the selector creation the non-trimmed `range` is used 🤔 
https://github.com/recogito/text-annotator-js/blob/80c2f9235ef27b2e57ff84a23d1f100a7b377e83/packages/text-annotator/src/SelectionHandler.ts#L85
Wouldn't it be better to use the `trimmed` one to exclude any non-textual nodes? 🤔

**Comment by rsimon** [comment]
Thanks! Merged the PR. And you are right of course: it should be the trimmed range that should define the selector. I made that change just now.

**Comment by oleksandr-danylchenko** [comment]
Thanks for taking a look!
