### ISSUE TITLE
Does this project intend to implement the W3C Web Annotation?

### ISSUE THREAD

**Issue by nigini** [recogito/text-annotator-js#32]
Hello there,
Just wondering if you intend to implement the [W3C Web Annotation Standards](https://www.w3.org/TR/annotation-model/)?

Either way, it may be worth adding this piece of information to your README file.

Best luck.

**Comment by rsimon** [comment]
Hi @nigini,

for various reasons, the Text Annotator uses a data model internally that deviates from the W3C spec in small ways. However, there's a built-in crosswalking feature that will make the external API (= all the methods on the `anno` instance object) work with different data models. 

A W3C Web Anno crosswalk is included out of the box. You just have to switch it on, like so:

```js
import { createTextAnnotator, W3CTextFormat } from '@recogito/text-annotator';

window.onload = async () => {
  const elem = document.getElementById('my-text-container');

  const anno = createTextAnnotator(elem, {
    adapter: W3CTextFormat('https://www.gutenberg.org', elem)
  });
```

(Thx to @oleksandr-danylchenko for contributing the adapter!)
