### ISSUE TITLE
Implement the `Text Quote Selector` model that will match the W3C spec

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#4]
## Current State
During the walk through the lib code, I found the new [`TextSelector`](https://github.com/recogito/text-annotator-js/blob/8ccace6254f599d25ebb6ddbac8c69fa571c1cf0/packages/text-annotator/src/model/TextAnnotation.ts#L9-L13) added during the [internal data model shift](https://matrix.to/#/!PKeiixCnYWBHzKrJUT:gitter.im/$f2tJSZNtj3e58bSMZKGs1L5GqKLkjo4_O1682nz2KRY?via=gitter.im&via=messenger.ukp.informatik.tu-darmstadt.de)
It covers the functionality of both the [`Text Quote Selector`](https://www.w3.org/TR/annotation-model/#text-quote-selector) and the [`Text Position Selector`](https://www.w3.org/TR/annotation-model/#text-position-selector) in a more concise format of a single object:
https://github.com/recogito/text-annotator-js/blob/8ccace6254f599d25ebb6ddbac8c69fa571c1cf0/packages/text-annotator/src/model/TextAnnotation.ts#L15-L27

## Issue Description
Unfortunately, its _`Text Quote Selector` representation_ is only partial now, utilizing the [`exact`](https://www.w3.org/TR/annotation-model/#text-quote-selector:~:text=associated%20with%20it.-,exact,-Property) prop, _without capturing the [`prefix`](https://www.w3.org/TR/annotation-model/#text-quote-selector:~:text=1%20exact%20property.-,prefix,-Property) and [`suffix`](https://www.w3.org/TR/annotation-model/#text-quote-selector:~:text=more%20than%201.-,suffix,-Property)_. That could be sufficient if we know that the `target`'s `source` is cemented and will never change. But in our use case, we expect that the _`source` is mutable_ and we'll need to _"migrate"/"restore" the existing annotations on the updated content_. _Relying on the `exact` match can be deceiving during that process._ 

### Broken behavior example
1. A user selects the word "cat" in the 1st paragraph, within the sentence "walking cat in the park"
2. Another paragraph is added at the start with the sentence "my cat really likes playing with toys"
3. During the "migration" process we'll look for the `exact` match in the updated `source` and will add the annotation to the new sentence with the word "cat" in it. The original annotation will get lost

## Why Change is Needed
Changing the `quote` property shape from the `string` to an object that will also store the `prefix` and `suffix` to distinguish between multiple copies of the same sequence of characters and prevent _most_ mismatches

## Possible Solutions
Changing the `quote` property shape from the `string` to the:
```ts
export interface TextSelector {
  quote: {
    exact: string;
    prefix: string;
    suffix: string;
  },
  ...
}
```
and capturing the both the `prefix` and `suffix` on selection: 
https://github.com/recogito/text-annotator-js/blob/8ccace6254f599d25ebb6ddbac8c69fa571c1cf0/packages/text-annotator/src/SelectionHandler.ts#L17

## Additional Information
Discussion about that change started in [this Gitter thread](https://matrix.to/#/!PKeiixCnYWBHzKrJUT:gitter.im/$4aAPrxCQ1hZR04LrNVSbqR-aDOdhZTbJCDFOOiI1X64?via=gitter.im&via=messenger.ukp.informatik.tu-darmstadt.de)

## Assignees
I would like to start working on this change myself and then submit the PR for review

**Comment by oleksandr-danylchenko** [comment]
[Here's](https://matrix.to/#/!PKeiixCnYWBHzKrJUT:gitter.im/$WCrn2trJO88_jPGJd8QRjB0Qme6iWwBjlOCBF4mHQW4?via=gitter.im&via=messenger.ukp.informatik.tu-darmstadt.de) the suggestion about using the "adapter" for extending the `quote` functionality. They look like a sensible place to map the W3C WebAnno `exact` prop to the current `quote`. But I'm not sure that _just them_ can be sufficient for the aforementioned need of having the `exact`, `prefix`, and `suffix` props on the selector 🤔 




I understand They could be enough if we would like to deal with only the `exact` prop

**Comment by rsimon** [comment]
I'd love to see this addition! I agree, it's an open question of whether computation of prefix & suffix can happen in the adapter alone, or whether this is something that would need to be added to the core (e.g. [here](https://github.com/recogito/text-annotator-js/blob/main/packages/text-annotator/src/SelectionHandler.ts#L7-L24)).

(I'm also wondering if there's a small risk of adding too much memory-consuming bloat if each annotation carries prefix and suffix. But TBH it's probably negligible by today's standards.)

**Comment by oleksandr-danylchenko** [comment]
> it's an open question of whether computation of prefix & suffix can happen in the adapter alone, or whether this is something that would need to be added to the core (e.g. [here](https://github.com/recogito/text-annotator-js/blob/main/packages/text-annotator/src/SelectionHandler.ts#L7-L24)).

I would vote for having such a selection in the core instead of the adapter. Because there we already have access to everything we would like to know about the container, ranges, etc. Forwarding all that the adapter that might act like a pure mapper seems like an overhead.

> (I'm also wondering if there's a small risk of adding too much memory-consuming bloat if each annotation carries prefix and suffix. But TBH it's probably negligible by today's standards.

It depends on what size of the `prefix`/`suffix` we would like to capture. I think that ~10 characters might be enough and not too wasteful. Also, there can be an option to disable the capturing of the `prefix`/`suffix` and always just assign `null`. I think that it can even be enabled by default. As most of the users will only need the `Text Position Selector` and the `exact` quote is more than enough

**Comment by rsimon** [comment]
Agreed - also, let's not overcomplicate from the start: as you say, all the info that's needed to compute prefix and suffix are in that function already.
