### ISSUE TITLE
Add persistence for `target.id` property of the `W3CTextAnnotation` on parsing/serialization

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#49]
## Issue
According to W3C Anno spec, the `target` can have the [`id` prop](https://arc.net/l/quote/zqaqaywb):
```json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno18",
  "type": "Annotation",
  "body": {},
  "target": {
    "id": "http://example.org/photo1",
    "type": "Image"
  }
}
```
This also matches the expectation of my application to assign specific IDs to the targets depending on which element the annotation was done.

Unfortunately, using the `W3CTextFormat` adapter I noticed that the assigned `id` is getting lost after parsing and won't be serialized back 👀
<img width="444" src="https://github.com/recogito/text-annotator-js/assets/68850090/310e3e48-a0d6-4c21-b0b9-41f365992921" />
<img width="444" src="https://github.com/recogito/text-annotator-js/assets/68850090/5e53f497-e4f6-47cc-bd7d-de9fecad8b48" />

## Possible Solution
I see the next `id`s connection between the internal and W3C models: 
| Internal | | W3C |
|--------|--------|--------|
| `target.selector[X].id` | ⇔ | `target[X].id` | 

So on parsing, we can assign the targets' id to `selector` entries and do the inverse process on serialization

**Comment by oleksandr-danylchenko** [comment]
Additionally, I think that not assigning the `id` to `TextAnnotationTarget` in the internal model is acceptable. Because they are already identified with the `.annotation` property due to the 1-1 connection

**Comment by oleksandr-danylchenko** [comment]
And... Maybe it's _worth_ assigning the ids to the selectors by default in the `rangeToSelector` function... I'm on the fence about that idea, because those ids won't be used by the library itself 🤷🏻‍♂️

**Comment by rsimon** [comment]
Just briefly: IDs need to stay on the targets, because this otherwise breaks all our realtime scenarios.

**Comment by oleksandr-danylchenko** [comment]
But there are no ids assigned to the targets now in the system 🤔

**Comment by rsimon** [comment]
Ah, wait - there are no ids on the target in the core model.

**Comment by rsimon** [comment]
So is this a change that just affects the W3C adapter? (Sorry, don't have time to look into the details myself right now.)

**Comment by oleksandr-danylchenko** [comment]
Yep, only the adapter and the `W3CAnnotationTarget` type: 
```ts
export interface W3CAnnotationTarget {

  id?: string;

  source: string;

  selector?: AbstractW3CSelector;

}
```
