### ISSUE TITLE
Fix usage of the A9S `Store` types instead of the `TextAnnotationStore` ones

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#57]
## Issue
When I was working on my custom plugin, I was following the [`TEIPlugin`](https://github.com/recogito/text-annotator-js/blob/main/packages/extension-tei/src/TEIPlugin.ts). And then I stumbled on a seemingly redundant coercion of the store: 
https://github.com/recogito/text-annotator-js/blob/018eb1eda9a7590c9ff4c232a9ba4f0660c74ff4/packages/extension-tei/src/TEIPlugin.ts#L46-L54

When I dug deeper I found a weird Typescript behavior difference between the `type` and `interface` definitions on re-assigning their properties...

![image](https://github.com/recogito/text-annotator-js/assets/68850090/6ea8edaf-e1e9-434a-a59d-7406853e4bc6)
![image](https://github.com/recogito/text-annotator-js/assets/68850090/6f2f6d67-5c1b-4c86-8eba-05de50ba1a14)
![image](https://github.com/recogito/text-annotator-js/assets/68850090/5bc668c0-47b4-4b32-8a39-f7ce59394e5c)

Moreover, after I replaced `type TextAnnotatorState = ...` with the `interface TextAnnotatorState extends AnnotatorState<TextAnnotation> {` - the `TEIPlugin` started to work w/o any coercions! 🪄 ✨ 🦄
![image](https://github.com/recogito/text-annotator-js/assets/68850090/cf7bb35c-d40b-4fbf-9c3f-fe040df20f90)
 
## Possible Solutions
Replace the: 
```ts
export type TextAnnotatorState = AnnotatorState<TextAnnotation> & {
}
```
with the:
```ts
export interface TextAnnotatorState extends AnnotatorState<TextAnnotation> {
}
```

**Comment by rsimon** [comment]
One of those moments where I think I will never understand TS... But, yes, looks good - thanks for figuring that out. (One lives and learns :-)

**Comment by oleksandr-danylchenko** [comment]
I'm also extremely surprised by such a sneaky difference 👀
Haven't seen it before and initially thought that it might be some older TS version bug. But no - we're using the latest TS already...

**Comment by oleksandr-danylchenko** [comment]
Gosh... This is not the end... 
<img width="730" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/ba577d70-49e0-48ce-a966-ef026fb9bf50">
