### ISSUE TITLE
Implement default W3C format adapter

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#6]
## Current State
According to the [discussion in Gitter](https://matrix.to/#/!PKeiixCnYWBHzKrJUT:gitter.im/$speczEklGPPVks1JeknwjAupkUvjjsFBiZxPVoLziZw?via=gitter.im&via=messenger.ukp.informatik.tu-darmstadt.de):
> Annotorious v3 internally uses a model that's aligned with W3C, but it's not exactly identical. Consider it a slightly derived model that is meant for representing internal state: it's designed to work fast, with no need for constant runtime crosswalks.
> 
> In addition, there are "adapters", that will handle the crosswalking to W3C (or potentially other formats - COCO etc.).
> 
> So far, Annotorious v3 ships with a default [W3C format adapter implementation](https://github.com/annotorious/annotorious/blob/3.x/packages/annotorious/src/model/w3c/W3CImageFormatAdapter.ts). The adapter handles the crosswalking for everyone who wants to use the WebAnno spec. But it crosswalks only "at the edges" of the library, as it were.

## Issue Description
> **The crosswalk adapter is not yet implemented in the Text Annotator! Only in Annotorious.**

## Why Change is Needed
Such an adapter for the `TextAnnotator` would be useful for the users that need to persist the annotations in the classic W3C WebAnnotaion Model format and utilize the [annotation-protocol](https://www.w3.org/TR/annotation-protocol/).

## Possible Solutions
Create a built-in adapter called `W3CTextFormatAdapter` with `parseW3CTextAnnotation` & `serializeW3CTextAnnotation`. Such an adapter can be opted-in by a library user if they want to follow the W3C spec on their side.
The adapter should support mapping for such properties as: 
- `@context`
- `id`
- `type`
- `body` and its sub-properties*
- `target` and its sub-properties**

But all the other possible properties from the W3C WebAnno spec like: `generator`, `generated`, `audience`, `stylesheet` should be just recorder/serialized w/o any changes. Because they are not being used during the lifecycle of the package/

_*`body.source`, `body.rights` will be removed from the W3C annotation payload on parsing because there is no match for them in `AnnotationBody`
**`target.styleClass`,`target.accessibility`, `target.state` will be removed from the W3C annotation payload on parsing because there is no match for them in `TextAnnotationTarget`_

## Additional Information
Discussion about that change started in [this Gitter thread](https://matrix.to/#/!PKeiixCnYWBHzKrJUT:gitter.im/$4aAPrxCQ1hZR04LrNVSbqR-aDOdhZTbJCDFOOiI1X64?via=gitter.im&via=messenger.ukp.informatik.tu-darmstadt.de)

## Assignees
I would like to start working on this change myself and then submit the PR for review

**Comment by rsimon** [comment]
❤️ This sounds perfect - happy to accept a PR for this!
