### ISSUE TITLE
React package: convenience re-exports

### ISSUE THREAD

**Issue by rsimon** [recogito/text-annotator-js#85]
Hi @oleksandr-danylchenko,

I wanted to get your thoughts on re-exporting the types & classes from `@annotorious/*` and the `@recogito/text-annotator` package via the `@recogito/react-text-annotator`. I'm starting a new (mini) project just now, and realized that  `@recogito/react-text-annotator` doesn't currently re-export any of the essential definitions.

Do you think it would make sense to extend this? How are you handling this in your current setup? (Which is React-based, right?) Are you installing all of the following as dependencies?
- `@annotorious/react` (for the `<Annotorious>` context)
- `@recogito/text-annotator` (for basic types like `W3CTextAnnotation` and the FormatAdapter)
- `@recogito/react-text-annotator`

**Comment by oleksandr-danylchenko** [comment]
> Do you think it would make sense to extend this?

I think it makes perfect sense. It makes setting up the project easier, as you'll just need to install a single overarching dependency. And it makes the import definition clearer.

> How are you handling this in your current setup? (Which is React-based, right?) Are you installing all of the following as dependencies?

Exactly! I installed all the dependencies in the project and I used imports from multiple sources at once:
<img width="666" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/b15d922b-a3ed-4815-80e7-132f7ed125d2">
<img width="666" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/6fdb40b7-8489-422d-9fae-4a895cc6225b">

**Comment by rsimon** [comment]
Ok, thanks for clarifying! What's the reason you are importing `@annotorious/core` in addition to `annotorious/react`. (Looks like there's something in the `core` I should also re-export via `react`?). Also: you're not actually using `openseadragon`, right? That's also something that the build will complain about? (I think I noticed this previously, but then didn't find a solution for it...)

**Comment by rsimon** [comment]
Another question: do you have thoughts on how to handle the React `ref` of the text element, that's needed for the W3C format adapter? I'm now also using W3C annotations in my new project, and it's a weird kind of dependency that would be nice to find a good solution for. This is what it looks like on my end:

```tsx
<div ref={el}>
  {(text && annotations && el.current) && (
    <TextAnnotator
      adapter={W3CTextFormat('5db80aa5-8a27-4539-aeb3-bddf3abc0098', el.current)}>
      {text}
    </TextAnnotator>
  )}
</div>
```

**Comment by rsimon** [comment]
Ah, and maybe as a more general question: do you have thoughts on a kind of "controlled mode" for annotations, something like the below. I probably won't have the time to build it any time soon (and I'd definitely "emulate" it via the standard annotator store). But it seems like it would simplify things for small projects that have only few annotations and/or no realtime collaboration requirements.

```
<TextAnnotator
    adapter={W3CTextFormat('5db80aa5-8a27-4539-aeb3-bddf3abc0098', el.current)}
    annotations={annotations} 
    onChange={setAnnotations}>
    {text}
</TextAnnotator>
```

**Comment by oleksandr-danylchenko** [comment]
> Ok, thanks for clarifying! What's the reason you are importing `@annotorious/core` in addition to `annotorious/react`. (Looks like there's something in the `core` I should also re-export via `react`?). 

After your message, I revisited the `@annotorious/core` imports and it seems like I was only using them for the `Color` type & the `Origin` enum. Which are already re-exported from the `@annotorious/react`. So I ended up removing the `@annotorious/core` from the deps list 👌🏻 

> Also: you're not actually using `openseadragon`, right? That's also something that the build will complain about? (I think I noticed this previously, but then didn't find a solution for it...)

No, I don't use the `openseadragon` and I think it's leftover from the "era" when I tried to distribute the forked repo via [`gitpkg`](https://gitpkg.vercel.app/about/). And the `yarn` was complaining that it could not find the `openseadragon` dependency to compile the package locally on `postinstall`. 
So after your question, I revisited that dependency, and could safely remove it 👌🏻 
<img width="400" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/521b320b-489d-4931-a746-af779fedd71c">

**Comment by oleksandr-danylchenko** [comment]
> Another question: do you have thoughts on how to handle the React `ref` of the text element, that's needed for the W3C format adapter? I'm now also using W3C annotations in my new project, and it's a weird kind of dependency that would be nice to find a good solution for. This is what it looks like on my end:
> 
> ```tsx
> <div ref={el}>
>   {(text && annotations && el.current) && (
>     <TextAnnotator
>       adapter={W3CTextFormat('5db80aa5-8a27-4539-aeb3-bddf3abc0098', el.current)}>
>       {text}
>     </TextAnnotator>
>   )}
> </div>
> ```

I faced the same weird dependency myself 👌🏻  
And came up with an alternative adapted definition through the callback:
```tsx
export const WebtextsAnnotator: FC<Props> = (props) => {
        ...
	const w3cAdapter = useCallback(
		(container: HTMLElement) => W3CTextFormat(host, container),
		[host]
	);

	return (
		<Annotorious key={pageFamilyId}>
			<TextAnnotator adapter={w3cAdapter} renderer="CANVAS">
			        ...
				{children}
			</TextAnnotator>
		</Annotorious>
	);
};
```
Using the callback you're ensured that the `container` is defined on the adapter creation. And that `container` is the wrapper created by the `TextAnnotator`:
https://github.com/recogito/text-annotator-js/blob/2018b9f4b5e6c5585ab74c59372981345c0bdda1/packages/text-annotator-react/src/TextAnnotator.tsx#L55-L59
And here's the PR where I added callback adapter format - https://github.com/recogito/text-annotator-js/pull/40

---

Although, in your case, you wanna provide the _parent_ of the annotator as the `container` 🤔 
Is there some positioning/styling reason for that? As I would imagine the `div` wrapping the the `TextAnnotator` and the one created within should act in the same way 🤔

**Comment by oleksandr-danylchenko** [comment]
> Ah, and maybe as a more general question: do you have thoughts on a kind of "controlled mode" for annotations, something like the below. I probably won't have the time to build it any time soon (and I'd definitely "emulate" it via the standard annotator store). But it seems like it would simplify things for small projects that have only few annotations and/or no realtime collaboration requirements.
> 
> ```
> <TextAnnotator
>   adapter={W3CTextFormat('5db80aa5-8a27-4539-aeb3-bddf3abc0098', el.current)}
>   annotations={annotations} 
>   onChange={setAnnotations}>
>   {text}
> </TextAnnotator>
> ```

At some point, I even wanted to file an "issue" for such a feature myself way back ago. As in my annotator lib, the consuming app is responsible for the state and persistence, either in local storage or on the server. So the "controlled" mode would make sense. 
But then I decided that we might face unobvious conflicts with the event-based store. For example, when the parent app adds an item to the `annotation` array, should the `createAnnotation` even get fired? Or how should we track the update/delete of an item within the array?

However, after working with the store more closely, now I'm realizing that all that interaction might be simpler than I anticipated. _Why wouldn't we just run the `setAnnotations(props.annotations, replace: true)` under the hood any time the `annotations` prop changes?.._ It feels like _a pretty safe option to me_. Those annotations bypass the flow of the events and trigger the re-render of the chosen renderer. The only thing that isn't clear yet, is whether we should mark those annotations with the `Origin.REMOTE` like the `setAnnotations` does by default 🤔. Because when the "onChange" runs, technically, those annotations are generated locally.

In conclusion, I should say that it might be a convenient addition, which makes the annotator work more like an input. At the same time, I think that the current methods of interacting with the store are sufficient for my needs. It's even more convenient for me to listen to the `createAnnotation`/`updateAnnotation`/`deleteAnnotation` individually to track the changes and set the initial annotations via the `setAnnotations`:
```tsx
export const AnnotatorApi: FC<Props> = (props) => {
	const { pageFamilyId, api } = props;

	const r = useAnnotator();

	useEffect(() => {
		if (r && api) {
			api
				.loadPage(pageFamilyId)
				.then((annotations) => r.setAnnotations(sortBy(annotations, 'created')))
				.catch((e) => console.error(`Failed to load annotations for page: ${pageFamilyId}`, e));
		}
	}, [r, api, pageFamilyId]);

	/**
	 * Registers event listeners for creating, updating, and deleting annotations
	 * to fire respective API calls to persist the changes
	 */
	useEffect(() => {
		if (!r || !api) return;

		const handleCreateAnnotation = (annotation) => api.create?.(annotation);
		r.on('createAnnotation', handleCreateAnnotation);

		const handleUpdateAnnotation = (annotation) => api.update?.(annotation);
		r.on('updateAnnotation', handleUpdateAnnotation);

		const handleDeleteAnnotation = (annotation) => api.delete?.(annotation.id);
		r.on('deleteAnnotation', handleDeleteAnnotation);

		return () => {
			r.off('createAnnotation', handleCreateAnnotation);
			r.off('updateAnnotation', handleUpdateAnnotation);
			r.off('deleteAnnotation', handleDeleteAnnotation);
		};
	}, [api, r]);

	return null;
};

```

**Comment by oleksandr-danylchenko** [comment]
Back to the `openseadragon` dependency question. I found out that the build passes properly even w/o it:
<img width="644" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/03bee0af-e2bf-4e8c-9839-9fbdd1b507bb">

But the `Storybook` won't start w/o the one 👁️ 
<img width="747" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/084b7f58-ddb5-4b45-897e-602c219a3085">

So I added the `openseadragon` as the dev dependency + optional peer for my lib too:
<img width="339" alt="image" src="https://github.com/recogito/text-annotator-js/assets/68850090/267b9242-b9a5-47b2-9e2a-dfc31f634f4b">

**Comment by rsimon** [comment]
Thanks for looking into this! Ok, so it seems the re-exports from `@annotorious/react` are fine. I'll update those for `@recogito/react-text-annotator`.

Ah - I completely forgot about your PR that fixes the W3CAdapter problem. Well... issue solved then 😄. (I really just fiddled around with the ref to make sure the ref is defined, and the TextAnnotator doesn't get initialized before it it.)

About `openseadragon`. Ok, that seems sensible to me. If you are just consuming `@recogito/react-text-annotator` that would work without `openseadragon`. If you create your own library on top of `@recogito/react-text-annotator`, then re-declaring `openseadragon` as an optional peer feels ok, I believe.

The controlled mode will be a bigger issue. I believe we'd need to declare the updates as `REMOTE`, because local updates would trigger the lifecycle events - and would also propagate across the channel in multi-user scenarios. Even with `REMOTE` it might still a bit of a potential can of worms that would need to thoroughly tested, for any possible problems or gotchas. But, in any case, your suggestion sounds good. Perhaps not such a huge issue after all. (I had initially thought I'd have to build a full diff computation for every update... but maybe not needed after all.)

**Comment by oleksandr-danylchenko** [comment]
I think that this issue can be closed now. As the re-exports were successfully added and can already be used
