### ISSUE TITLE
The unsorted highlights can lead to incorrect overlapping order

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [recogito/text-annotator-js#94]
## Issue
I noticed that the new highlights can unpredictably appear under the older ones. It's because the `highlights` we pass to the renderers are obtained from the annotations in the viewport. When we search for them, _there are no guarantees of an order_ in the obtained set:
https://github.com/recogito/text-annotator-js/blob/9e885521d6b36fcda74d6b26d2eee2ba25ae413e/packages/text-annotator/src/highlight/baseRenderer.ts#L92-L98
https://github.com/recogito/text-annotator-js/blob/9e885521d6b36fcda74d6b26d2eee2ba25ae413e/packages/text-annotator/src/highlight/baseRenderer.ts#L106

And not having an order, may lead to undesired overlaps between the highlights, when the newer one appears under the older one: 

https://github.com/recogito/text-annotator-js/assets/68850090/24111c2e-3834-4690-b1df-169c94e005a6

https://github.com/recogito/text-annotator-js/assets/68850090/6cece6df-105b-4a77-9467-c16ff1b6575a

## Possible Solution
A solution here is _**to sort the highlights before drawing them out**_:
1. The most basic sorting can be implemented based on the `annotation.targer.created` property:
    ```ts
    const sortedHighlights = [...highlights].sort((highlightA, hightlightB) => {
      const { annotation: { target: { created: createdA } }} = highlightA;
      const { annotation: { target: { created: createdB } }} = hightlightB;
      return createdA.getTime() - createdB.getTime();
    })
    ```
    That will guarantee that the renderer will properly stack the highlights based on their creation time
2. Or the sorting function can be made configurable too, like the `filter`

**Comment by rsimon** [comment]
I'm not yet convinced this can't be solved more easily through other means. (E.g. the style function already gets a Z index, which you could possibly use. Or it could be the responsibility of the renderer. The most solid option would like be to always render the annotation with the smallest area on top - which is exactly how the style z index works.) Which renderer are you using in the example?

**Comment by oleksandr-danylchenko** [comment]
I'm using the `CANVAS` renderer. Unfortunately, it doesn't have an applicable Z index for individual highlights. Instead, it requires to rely on the drawing order. The later something draws - the higher it'll appear in the stack

**Comment by oleksandr-danylchenko** [comment]
> The most solid option would like be to always render the annotation with the smallest area on top

I'm not sure about that one 🤔 
Because I can make the selection over the smaller highlight, and I would expect that the newer one will be placed at the top:
![image](https://github.com/recogito/text-annotator-js/assets/68850090/2f027105-682b-41b9-b55a-71774153db0e)

**Comment by oleksandr-danylchenko** [comment]
Also, the examples became much more apparent when you disable the default browser's selection highlight: 
```css
*::selection {
  background: none;
}
```
We decided to use only the canvas for the selection visualization because the default one has a bunch of discrepancies between the browsers. 
In Chrome, it won't get discarded on the focus change, but in Safari & Firefox - it will. So it's easier to emulate it everywhere than instead of trying to apply some browser-specific hacks
